name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file docker/php/Dockerfile.baseimage --tag appointly/appointment-service:$(git rev-parse HEAD)

  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
